// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2HE73D8nHAokjIW2sKmzakMuOkqI2ldM',
    appId: '1:596210769223:web:b52ff0f04e40be0fa48062',
    messagingSenderId: '596210769223',
    projectId: 'fyp-app-8bd23',
    authDomain: 'fyp-app-8bd23.firebaseapp.com',
    storageBucket: 'fyp-app-8bd23.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTrMKT_oq520ZA9kUSnLtsNVA9ifzfKIQ',
    appId: '1:596210769223:android:3786102c87fe0bf9a48062',
    messagingSenderId: '596210769223',
    projectId: 'fyp-app-8bd23',
    storageBucket: 'fyp-app-8bd23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXFin4_N-kXObsHKg8GkdR_L_C-55I718',
    appId: '1:596210769223:ios:396d773d15bd1920a48062',
    messagingSenderId: '596210769223',
    projectId: 'fyp-app-8bd23',
    storageBucket: 'fyp-app-8bd23.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXFin4_N-kXObsHKg8GkdR_L_C-55I718',
    appId: '1:596210769223:ios:396d773d15bd1920a48062',
    messagingSenderId: '596210769223',
    projectId: 'fyp-app-8bd23',
    storageBucket: 'fyp-app-8bd23.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2HE73D8nHAokjIW2sKmzakMuOkqI2ldM',
    appId: '1:596210769223:web:0e58f32b2c0458b5a48062',
    messagingSenderId: '596210769223',
    projectId: 'fyp-app-8bd23',
    authDomain: 'fyp-app-8bd23.firebaseapp.com',
    storageBucket: 'fyp-app-8bd23.firebasestorage.app',
  );
}
